name: CI
on: [pull_request]
jobs:
  ci:
    uses: ucgmsim/meta-ci-action/.github/workflows/ci.yml@main
    with:
      package-dir: imdb
      uv-extra-args: "--all-groups"
      enable-coverage: true
      cov-package: imdb
